### ISSUE TITLE
Idp sertifikası, X509 

### ISSUE THREAD

**Issue by HTC37** [FreeFlarum/flarum-multitenant#11]
https://github.com/FreeFlarum/flarum-multitenant/blob/ad990f698ce08b11cae410ceb30f3ba27759e6b7/vendor/flarum-lang/turkish/locale/askvortsov-saml.yml#L23

**Comment by luceos** [comment]
@HTC37 suggestions to translations can be done at the language package itself, for Flarum Lang it is managed here: https://weblate.rob006.net/projects/flarum/askvortsov-saml/tr/

FreeFlarum does not manage nor maintain the languages.
